contentDir: content/zh
languageName: ä¸­æ–‡
languageCode: zh-CN
weight: 2
menu:
  main:
    - name: æœç´¢ğŸ”
      url: search
      weight: 1
    - name: åˆ†ç±»ğŸ—‚
      url: /categories
      weight: 5
    - name: æ ‡ç­¾ğŸ·ï¸
      url: /tags
      weight: 10
